"""
Create GitHub issues from discover_new JSON output.

The script intentionally consumes JSON output instead of importing crawler
internals, so issue creation can evolve independently from discover_new.py.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Any

import requests


GITHUB_API_URL = "https://api.github.com"
DEFAULT_TITLE_PREFIX = "Discovery candidate"


def load_candidates(path: str) -> list[dict[str, Any]]:
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        raise ValueError("discovery JSON must be a list")
    return [item for item in data if isinstance(item, dict)]


def candidate_issue_key(candidate: dict[str, Any]) -> str:
    url = str(candidate.get("url") or "").strip()
    if url:
        return url
    return str(candidate.get("title") or "").strip()


def select_issue_candidates(
    candidates: list[dict[str, Any]],
    *,
    include_review_buckets: set[str],
    limit: int,
) -> list[dict[str, Any]]:
    selected = [
        candidate
        for candidate in candidates
        if candidate.get("recommendation") == "needs_review"
        and candidate.get("review_bucket") in include_review_buckets
    ]
    return selected[:limit] if limit > 0 else selected


def format_bool(value: Any) -> str:
    return "true" if bool(value) else "false"


def render_verified_links(candidate: dict[str, Any]) -> str:
    checks = candidate.get("checks") or []
    if not checks:
        return "- No official code/model/dataset/project links found in arXiv metadata."

    lines = []
    for check in checks:
        if not isinstance(check, dict):
            continue
        status = check.get("status", "unknown")
        kind = check.get("kind", "unknown")
        url = check.get("url", "")
        reason = check.get("reason", "")
        lines.append(f"- `{status}` `{kind}`: {url} ({reason})")
    return "\n".join(lines) if lines else "- No verified links."


def render_issue_body(candidate: dict[str, Any], *, source_run: str | None = None) -> str:
    availability = candidate.get("artifact_availability") or {}
    llm_review = candidate.get("llm_review") or {}
    reasons = candidate.get("reasons") or []
    keyword_hits = candidate.get("keyword_hits") or []
    exclusion_hits = candidate.get("exclusion_hits") or []

    lines = [
        "## Discovery candidate",
        "",
        f"- Paper: {candidate.get('url', '')}",
        f"- Published: `{candidate.get('published', 'unknown')}`",
        f"- Source: `{candidate.get('source', 'unknown')}`",
        f"- Relevance: `{candidate.get('relevance', 'unknown')}`",
        f"- Recommendation: `{candidate.get('recommendation', 'unknown')}`",
        f"- Review bucket: `{candidate.get('review_bucket', 'unknown')}`",
        f"- Rule-based verified model link: `{format_bool(availability.get('has_verified_model_link'))}`",
        f"- Rule-based verified artifact link: `{format_bool(availability.get('has_verified_artifact_link'))}`",
        f"- Rule-based verified project page: `{format_bool(availability.get('has_verified_project_page'))}`",
    ]
    if keyword_hits:
        lines.append(f"- Keyword hits: {', '.join(str(hit) for hit in keyword_hits[:12])}")
    if exclusion_hits:
        lines.append(f"- Exclusion hits: {', '.join(str(hit) for hit in exclusion_hits)}")
    if reasons:
        lines.append(f"- Rule-based reasons: {'; '.join(str(reason) for reason in reasons)}")

    if llm_review:
        lines.extend([
            "",
            "## Optional LLM review",
            "",
            f"- Status: `{llm_review.get('status', 'unknown')}`",
        ])
        if llm_review.get("decision"):
            lines.append(f"- Decision: `{llm_review.get('decision')}`")
        if llm_review.get("entry_type"):
            lines.append(f"- Entry type: `{llm_review.get('entry_type')}`")
        if llm_review.get("reason"):
            lines.append(f"- Reason: {llm_review.get('reason')}")
        if llm_review.get("entry_summary"):
            lines.extend(["", "### Entry summary", "", str(llm_review.get("entry_summary"))])
        if llm_review.get("maintainer_summary"):
            lines.extend(["", "### Maintainer summary", "", str(llm_review.get("maintainer_summary"))])

    lines.extend([
        "",
        "## Verified links",
        "",
        render_verified_links(candidate),
        "",
        "## Abstract excerpt",
        "",
        str(candidate.get("summary") or ""),
    ])

    if source_run:
        lines.extend(["", "---", "", f"Generated by discovery workflow: {source_run}"])

    return "\n".join(lines).rstrip() + "\n"


def create_issue(
    *,
    repo: str,
    token: str,
    title: str,
    body: str,
    labels: list[str],
) -> str:
    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    payload: dict[str, Any] = {"title": title, "body": body}
    if labels:
        payload["labels"] = labels

    response = requests.post(f"{GITHUB_API_URL}/repos/{repo}/issues", headers=headers, json=payload, timeout=30)
    response.raise_for_status()
    data = response.json()
    return str(data.get("html_url") or "")


def main() -> int:
    parser = argparse.ArgumentParser(description="Create GitHub issues from discovery JSON output.")
    parser.add_argument("--input", required=True, help="Path to discover_new JSON output.")
    parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY", ""), help="GitHub repo in owner/name form.")
    parser.add_argument("--token", default=os.environ.get("GITHUB_TOKEN", ""), help="GitHub token with issues:write.")
    parser.add_argument("--limit", type=int, default=5, help="Maximum issues to create. Use 0 for no limit.")
    parser.add_argument(
        "--include-review-bucket",
        action="append",
        default=["normal"],
        choices=("normal", "ambiguous"),
        help="Review bucket to create issues for. Repeat to include more buckets.",
    )
    parser.add_argument("--label", action="append", default=[], help="Optional label to attach. Repeatable.")
    parser.add_argument("--title-prefix", default=DEFAULT_TITLE_PREFIX)
    parser.add_argument("--source-run", help="Optional workflow/run URL to include in issue body.")
    parser.add_argument("--dry-run", action="store_true", help="Print issues that would be created without writing.")
    args = parser.parse_args()

    candidates = load_candidates(args.input)
    selected = select_issue_candidates(
        candidates,
        include_review_buckets=set(args.include_review_bucket),
        limit=args.limit,
    )

    if not selected:
        print("No candidates selected for issue creation.")
        return 0

    if not args.dry_run and (not args.repo or not args.token):
        print("error: --repo/GITHUB_REPOSITORY and --token/GITHUB_TOKEN are required unless --dry-run is used.", file=sys.stderr)
        return 2

    for candidate in selected:
        title = f"{args.title_prefix}: {candidate.get('title', 'Untitled')}"
        body = render_issue_body(candidate, source_run=args.source_run)
        if args.dry_run:
            print(f"[dry-run] Would create issue: {title}")
            print(f"  key: {candidate_issue_key(candidate)}")
            continue

        url = create_issue(
            repo=args.repo,
            token=args.token,
            title=title,
            body=body,
            labels=args.label,
        )
        print(f"Created issue: {url}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
